# pubspec.yaml

name: golden_retriever_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  image_picker: ^1.0.0
  cupertino_icons: ^1.0.6
  intl: ^0.18.0
  rive: ^0.9.1
  flutter_svg: ^1.1.6
  flutter_secure_storage: ^7.0.1
  keyboard_avoider: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/cardnews/
    - assets/avatars/
    - assets/Backgrounds/
    - assets/icons/
    - assets/RiveAssets/

fonts:
  - family: Intel
    fonts:
      - asset: assets/Fonts/Inter-Regular.ttf
      - asset: assets/Fonts/Inter-SemiBold.ttf
        weight: 600
  - family: Poppins
    fonts:
      - assets: assets/Fonts/Poppins-Bold.ttf
        weight: 700